title: I just don't know what to do with GitHub pages
author: Nelson Vassalo
email: vassalo.nelson@gmai.com
description: > # this means to ignore newlines until "baseurl:"
  Tou aqui sรณ pra ver a bola

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
